import type { CollectionConfig } from "payload";
import path from "path";
import { fileURLToPath } from "url";

const dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Media library — image/file uploads stored on the server's disk (a persistent
 * Docker volume in production). `alt` is required so every image ships with SEO
 * alt text. Responsive sizes are generated by sharp for fast, right-sized
 * delivery.
 */
export const Media: CollectionConfig = {
  slug: "media",
  admin: { group: "Content" },
  access: {
    read: () => true, // public — images are served on the website
    create: ({ req: { user } }) => Boolean(user),
    update: ({ req: { user } }) => Boolean(user),
    delete: ({ req: { user } }) => Boolean(user),
  },
  upload: {
    // Absolute path on disk; overridable via env for the production volume.
    staticDir: process.env.PAYLOAD_MEDIA_DIR || path.resolve(dirname, "../../media"),
    mimeTypes: ["image/*", "application/pdf"],
    imageSizes: [
      { name: "thumbnail", width: 400, height: undefined, position: "centre" },
      { name: "card", width: 768, height: undefined },
      { name: "feature", width: 1280, height: undefined },
      { name: "hero", width: 1920, height: undefined },
    ],
    focalPoint: true,
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
      admin: { description: "Describe the image for SEO and accessibility (required)." },
    },
    {
      name: "caption",
      type: "text",
      admin: { description: "Optional caption shown under the image where used." },
    },
  ],
};
