// One-time local setup: create a .env for development if none exists, with a
// generated PAYLOAD_SECRET and a DATABASE_URI pointing at the dev Docker
// Postgres (docker-compose.dev.yml). Safe to re-run — never overwrites an
// existing .env.
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");

if (existsSync(envPath)) {
  console.log(".env already exists — leaving it untouched.");
  process.exit(0);
}

const port = process.env.ADAM_DB_PORT || "5432";
const secret = randomBytes(32).toString("hex");
const contents = `# Local development environment (generated by \`npm run setup\`; gitignored).
# The database matches docker-compose.dev.yml (start it with \`npm run db:up\`).
DATABASE_URI=postgresql://adam:adam@127.0.0.1:${port}/adam_cms
PAYLOAD_SECRET=${secret}
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# First admin created automatically by \`npm run seed\` (change after login):
ADMIN_EMAIL=admin@adam.qa
ADMIN_PASSWORD=changeme123
ADMIN_NAME=Administrator
`;

writeFileSync(envPath, contents, { mode: 0o600 });
console.log(`Created .env (DB on port ${port}, generated PAYLOAD_SECRET).`);
